Fake_csv_generator/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from schemas.views import login_page, SchemaListView, logout_user, SchemaCreateView,\
    schema_delete, SchemaDatasetListView


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', login_page, name='login'),
    path('schemas/', SchemaListView.as_view(), name='schemas'),
    path('logout/', logout_user, name='logout'),
    path('schema/create/', SchemaCreateView.as_view(), name='schema_create'),
    path('schema/delete/<int:pk>', schema_delete, name='schema_delete'),
    path('schema/datasets/<int:pk>', SchemaDatasetListView.as_view(), name='schema_datasets')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schemas/models.py
from django.db import models
from .choices import COLUMN_SEPARATOR, STRING_CHARACTER, TYPES, DATASET_STATUS


class Schema(models.Model):
    name = models.CharField(max_length=120, verbose_name='Name', blank=False)
    column_separator = models.CharField(max_length=20, verbose_name='Column separator',
                                        choices=COLUMN_SEPARATOR, blank=False)
    string_character = models.CharField(max_length=20, verbose_name='String character',
                                        choices=STRING_CHARACTER, blank=False)
    modified_date = models.DateField(verbose_name='Modified', auto_now=True)


class SchemaColumn(models.Model):
    schema = models.ForeignKey(Schema, on_delete=models.CASCADE)
    column_name = models.CharField(max_length=120, verbose_name='Column name', blank=False)
    column_type = models.CharField(max_length=50, choices=TYPES, blank=False, verbose_name='Type')
    range_from = models.IntegerField(verbose_name='From', blank=True, null=True)
    range_to = models.IntegerField(verbose_name='To', blank=True, null=True)
    order = models.IntegerField(verbose_name='Order', blank=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['schema', 'order'],
                name='unique order'
            )
        ]


class SchemaDataset(models.Model):
    schema = models.ForeignKey(Schema, on_delete=models.CASCADE)
    created = models.DateField(verbose_name='Created', auto_now=True)
    status = models.CharField(max_length=20, verbose_name='Status', choices=DATASET_STATUS,
                              default='processing', blank=False)
    link = models.CharField(max_length=120, verbose_name='link', blank=True, null=True)
    rows_quantity = models.IntegerField(verbose_name='rows_quantity', blank=False, null=True)
    task_id = models.CharField(max_length=120, verbose_name='task_id', blank=True, null=True)

# TODO Strings and Admin Views

schemas/views.py
import json

from celery.result import AsyncResult
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.http import Http404, JsonResponse
from .tasks import create_csv
from .models import Schema, SchemaColumn, SchemaDataset
from .choices import TYPES


def login_page(request):
    if request.user.is_authenticated:
        return redirect('schemas')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('schemas')
            else:
                messages.info(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    return redirect('login')


class SchemaListView(ListView):
    template_name = 'schemas.html'
    model = Schema
    queryset = Schema.objects.all()

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return super(SchemaListView, self).dispatch(*args, **kwargs)
        raise Http404

    def get_context_data(self, **kwargs):
        context = super(SchemaListView, self).get_context_data(**kwargs)
        return context


# TODO UpdateView

class SchemaCreateView(CreateView):
    model = Schema
    fields = ['name', 'column_separator', 'string_character']
    template_name = 'schema_new.html'

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return super(SchemaCreateView, self).dispatch(*args, **kwargs)
        raise Http404

    def get_context_data(self, **kwargs):
        context = super(SchemaCreateView, self).get_context_data(**kwargs)
        context['status'] = TYPES
        return context

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            schema_data = json.loads(self.request.POST.get('item_text'))
            schema = schema_data['schema']
            columns = schema_data['columns']
            if len(columns) == 0:
                return JsonResponse({'data': False}, safe=False)
            new_schema = Schema(name=schema['id_name'],
                column_separator=schema['id_column_separator'],
                string_character=schema['id_string_character'])
            new_schema.save()
            for key, a in columns.items():
                new_column = SchemaColumn(schema=new_schema, column_name=a['column_name'],
                    column_type=a['type_value'], range_from=a['from_range'],
                    range_to=a['to_range'], order=a['order'])
                new_column.save()
            return JsonResponse({'data': True}, safe=False)
        return Http404


def schema_delete(request, pk):
    try:
        schema = Schema.objects.get(pk=pk)
        schema.delete()
        return redirect("schemas")
    except Schema.DoesNotExist:
        return redirect("schemas")


class SchemaDatasetListView(ListView):
    model = SchemaDataset
    template_name = 'schema_dataset.html'

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_staff or not self.request.user.is_superuser:
            raise Http404
        return super(SchemaDatasetListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return SchemaDataset.objects.filter(schema_id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(SchemaDatasetListView, self).get_context_data(**kwargs)
        context['schema_id'] = self.kwargs['pk']
        return context

    def post(self, *args, **kwargs):
        if self.request.is_ajax():
            datasets_task_uuid = json.loads(self.request.POST.get('uuid'))
            response = {}
            for a in datasets_task_uuid['uuid']:
                task_result = AsyncResult(a)
                response[a] = task_result.status
                if task_result.status == 'SUCCESS':
                    schema_dataset = SchemaDataset.objects.get(task_id=a)
                    schema_dataset.status = 'ready'
                    schema_dataset.save()
            return JsonResponse(response, safe=False)
        new_dataset = SchemaDataset(schema_id=self.kwargs['pk'],
                                    rows_quantity=self.request.POST['rows_quant'])
        new_dataset.save()
        schema = new_dataset.schema
        columns = SchemaColumn.objects.filter(schema_id=schema.id).order_by('order')
        columns_data = {'dataset_id': new_dataset.id,
                        'rows_quantity': int(new_dataset.rows_quantity),
                        'delimiter': schema.column_separator,
                        'quotechar': schema.string_character,
                        'columns': {}}
        for col in columns:
            columns_data['columns'][col.column_name] = {'type': col.column_type,
                                                        'from': col.range_from,
                                                        'to': col.range_to}
        task = create_csv.delay(columns_data)
        new_dataset.task_id = task.id
        new_dataset.link = 'https://s3-eu-central-1.amazonaws.com/csvgenerator/'\
                           + str(new_dataset.id) + '.csv'
        new_dataset.save()
        return redirect('schema_datasets', pk=schema.id)

templates/base.html
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Schemas</title>

    {% include 'head_css.html' %}
    {% block script %}

    {% endblock %}

</head>
<body>
<header>
    <nav class="navbar navbar-expand-md navbar-light bg-light fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'schemas' %}">FakeCSV</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item active">
                        <a class="nav-link" aria-current="page" href="{% url 'schemas' %}" style="color: rgba(0, 0, 0, 0.8);">Shcemas</a>
                    </li>

                </ul>
                <span class="navbar-text">
              <ul class="navbar-nav me-auto mb-2 mb-md-2">
        <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="#">Hello, <b>{{ user.get_username }}</b></a>
        </li>
                  <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="{% url 'logout' %}">Logout</a>
        </li>

      </ul>
      </span>
            </div>
        </div>
    </nav>
</header>

{% block content %}

{% endblock %}
{% include "javascript.html" %}
</body>
</html>

templates/head_css.html
{% load static %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP"
      crossorigin="anonymous">


<style>
    a {
        text-decoration: none;
    }
</style>

templates/javascript.html
{% load static %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

templates/login.html
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    {% include 'head_css.html' %}

    <style>

        .card {
            position: absolute;
            width: 650px;
            height: 445px;
            left: 395px;
            top: 180px;

            background: #FFFFFF;
            border: 1px solid #E5E5E5;
            box-sizing: border-box;
            border-radius: 4px;
        }

        #Display_1 {
            font-family: "HelveticaNeue";
            margin-top: 2ch;
            margin-bottom: 2ch;
            font-size: 36px;
            line-height: 79px;
            display: flex;
            align-items: flex-end;
            color: #373A3C;

        }

        .btn {
            margin-left: auto;
            background: #0275D8;
            border: 1px solid #0275D8;
            box-sizing: border-box;
            border-radius: 4px;
            font-family: "HelveticaNeue";
            font-size: 16px;
            line-height: 21px;
            color: #FFFFFF;
        }
    </style>

</head>
<body>
<div class="card">
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
                <div class="d-flex justify-content-center">


                    <h3 id="Display_1">Login</h3>
                </div>
                <div class="d-flex justify-content-center form_container">
                    <form method="POST" action="">

                        <div class="input-group mb-3">
                            <input type="text" name="username" placeholder="Username" class="form-control">
                        </div>

                        <div class="input-group mb-2">
                            <input type="password" name="password" placeholder="Password" class="form-control">
                        </div>

                        <div class="d-flex justify-content-center mt-3 login_container">{% csrf_token %}
                            <input class="btn login_btn" type="submit" value="Login">
                        </div>
                    </form>

                </div>

                {% for message in messages %}
                    <p id="messages">{{ message }}</p>
                {% endfor %}

            </div>
        </div>
    </div>
</div>
</body>

</html>

templates/schema_dataset.html
{% include "base.html" %}
{% load crispy_forms_tags %}
{% block script %}
    <script type="text/javascript">


        setInterval(function () {
            var CSRFtoken = $('input[name=csrfmiddlewaretoken]').val();
            var uuid_list = []
            $('span[name ="processing"]').each(function () {
                uuid_list.push(this.id)
            })
            if (uuid_list.length > 0){
            $.ajax({
                type: "POST",
                url: "{% url 'schema_datasets' schema_id %}",
                data: {
                    uuid: JSON.stringify({ 'uuid': uuid_list }), csrfmiddlewaretoken: CSRFtoken
                },
                success: function (resp) {
                    $.each(resp, function (index, value) {
                        if (value == 'SUCCESS'){
                            $('#'+index).css('background-color', '#5CB85C')
                            $('#'+index).attr('name', 'Ready')
                            $('#'+index).text('Ready')
                            $('a[name = '+index+']').css('visibility', 'visible')
                        }
                    });
                }
            })
            }
        }, 5000);

    </script>

{% endblock %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 10ch">
            <div class="col-6">
                <h2>Data sets</h2>
            </div>
            <div class="col-6">
                <form class="row justify-content-end" action="{% url 'schema_datasets' schema_id %}" method="post">
                    {% csrf_token %}
                    <div class="col-1">
                        <label class="col-form-label" for="rows_quant_id">Rows:</label>
                    </div>
                    <div class="col-4">
                        <input type="number" name="rows_quant" class="form-control" id="rows_quant_id">
                    </div>
                    <div class="col-5">
                        <button type="submit" style="background: #5CB85C; border: 1px solid #5CB85C; color: #FFFFFF"
                                class="btn btn-primary">Generate data
                        </button>
                    </div>
                </form>
            </div>

            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Created</th>
                    <th scope="col">Status</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for a in schemadataset_list %}
                    <tr>
                        <th scope="row">{{ a.id }}</th>
                        <td>{{ a.created }}</td>
                        <td>{% if a.status == "processing" %}
                            <span style="background-color: #6c757d" name="{{ a.status }}" id="{{ a.task_id }}" class="badge">{{ a.get_status_display }}</span>
                        {% else %}
                            <span style="background: #5CB85C" class="badge">{{ a.get_status_display }}</span>
                        {% endif %}</td>
                        <td><a name="{{ a.task_id }}" href="{{ a.link }}"
                               style="visibility: {% if a.status == "processing" %}hidden{% else %}visible{% endif %}">Download</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/schema_detail.html
{% include "base.html" %}
{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 10ch">
            <div class="col-sm">
                <h2 class="col-10">New schemas</h2>
            </div>

            <div class="col-2">
                <button class="btn btn-success justify-content-end" style="background: #5CB85C; border: 1px solid #5CB85C; " type="button">Submit</button>
            </div>
        </div>


        <form class="row g-3">
            <div class="col-md-12">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control" id="name">
            </div>
            <div class="col-md-12">
                <label for="col_sep" class="form-label">Column separator</label>
                <input type="text" class="form-control" id="col_sep">
            </div>
            <div class="col-md-12">
                <label for="stringChar" class="form-label">String character</label>
                <input type="text" class="form-control" id="stringChar">
            </div>

            <div class="container">
                <div class="row" style="margin-top: 10ch">
                    <div class="col-sm">
                        <h2 class="col-12">Schemas columns</h2>
                    </div>
                </div>
                <div class="col-4">
                    <label for="inputAddress" class="form-label">Column name</label>
                    <input type="text" class="form-control" id="inputAddress">
                    <div class="col-3">
                        <label for="inputState" class="form-label">Type</label>
                        <select id="inputState" class="form-select">
                            <option selected>Choose...</option>
                            <option>...</option>
                        </select>
                    </div>
                    <div class="col-1">
                        <label for="inputAddress2" class="form-label">From</label>
                        <input type="number" class="form-control" id="inputAddress2">
                    </div>
                    <div class="col-1">
                        <label for="inputAddress2" class="form-label">To</label>
                        <input type="number" class="form-control" id="inputAddress2">
                    </div>
                    <div class="col-2">
                        <label for="inputAddress2" class="form-label">Order</label>
                        <input type="number" class="form-control" id="inputAddress2">
                    </div>
                    <div class="col-1">
                        <input type="text" class="form-control" id="inputAddress2">
                    </div>

                    <div class="col-md-4">
                        <label for="inputState" class="form-label">State</label>
                        <select id="inputState" class="form-select">
                            <option selected>Choose...</option>
                            <option>...</option>
                        </select>
                    </div>
                </div>
            </div>
        </form>
    <div class="card">
        <div class="container">
                <div class="row" style="margin-top: 10ch">
                    <div class="col-sm">
                        <h2 class="col-12">Schemas columns</h2>
                    </div>
                </div>
                <div class="col-4">
                    <label for="inputAddress" class="form-label">Column name</label>
                    <input type="text" class="form-control" id="inputAddress">
                    <div class="col-3">
                        <label for="inputState" class="form-label">Type</label>
                        <select id="inputState" class="form-select">
                            <option selected>Choose...</option>
                            <option>...</option>
                        </select>
                    </div>
                    <div class="col-1">
                        <label for="inputAddress2" class="form-label">From</label>
                        <input type="number" class="form-control" id="inputAddress2">
                    </div>
                    <div class="col-1">
                        <label for="inputAddress2" class="form-label">To</label>
                        <input type="number" class="form-control" id="inputAddress2">
                    </div>
                    <div class="col-2">
                        <label for="inputAddress2" class="form-label">Order</label>
                        <input type="number" class="form-control" id="inputAddress2">
                    </div>
                    <div class="col-1">
                        <input type="text" class="form-control" id="inputAddress2">
                    </div>

                    <div class="col-md-4">
                        <label for="inputState" class="form-label">State</label>
                        <select id="inputState" class="form-select">
                            <option selected>Choose...</option>
                            <option>...</option>
                        </select>
                    </div>
                </div>

    </div>
    </div>
{% endblock %}

templates/schemas.html
{% include "base.html" %}
{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 10ch">
            <div class="col-sm">
                <h2 class="col-10">Data Schemas</h2>
            </div>
            <div class="col-2">
                <a href="{% url 'schema_create'%}" class="btn btn-info" style="background: #5CB85C; border: 1px solid #5CB85C; color: #FFFFFF" role="button">New Schema</a>
{#                <button class="btn btn-success justify-content-end" style="background: #5CB85C; border: 1px solid #5CB85C;" type="button">New Schema</button>#}
            </div>
        </div>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Modified</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for a in schema_list %}
            <tr>
                <th scope="row">{{ a.id }}</th>
                <td><a href="{% url 'schema_datasets' a.pk %}" >{{ a.name }}</a></td>
                <td>{{ a.modified_date }}</td>
                <td><a href="javascript:void(0)" onclick="alert('This feature will be available soon')">Edit schema </a><a href="{% url 'schema_delete' a.pk %}" style="color: #D9534F; padding-left:3em"> Delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}